version: "3.9"
services:
  tool:
    build: .
    environment:
      - POSTGRES_HOST=timescale
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=topsecret
      - POSTGRES_DATABASE=homework
    volumes:
      - ./query_params.csv:/query_params.csv
    links:
      - timescale
    depends_on:
      timescale:
        condition: service_healthy
    entrypoint: "./bench"
    command: "-file /query_params.csv"
  timescale:
    image: timescale/timescaledb:latest-pg12
    environment:
      - POSTGRES_PASSWORD=topsecret
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
      - ./cpu_usage.sql:/cpu_usage.sql
      - ./cpu_usage.csv:/cpu_usage.csv
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres && psql -U postgres -lqtA | grep -q \"^homework|\""]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 15s
